#!/usr/bin/env nix-shell
#!nix-shell -i bash -p nix-prefetch
set -euxo pipefail

OUT="_sources.nix"
URL="https://api.fontshare.com/v2/fonts/download"
FONTS=(
    "aktura"
    "alpino"
    "amulya"
    "array"
    "author"
    "bespoke-sans"
    "bespoke-serif"
    "bespoke-slab"
    "bespoke-stencil"
    "bevellier"
    "bonny"
    "boska"
    "boxing"
    "britney"
    "cabinet-grotesk"
    "chillax"
    "chubbo"
    "clash-display"
    "clash-grotesk"
    "comico"
    "erode"
    "excon"
    "expose"
    "gambarino"
    "gambetta"
    "general-sans"
    "hind"
    "hoover"
    "kalam"
    "karma"
    "khand"
    "kihim"
    "kohinoor-zerone"
    "kola"
    "melodrama"
    "neco"
    "new-title"
    "nippo"
    "pally"
    "panchang"
    "paquito"
    "pencerio"
    "pilcrow-rounded"
    "plein"
    "poppins"
    "pramukh-rounded"
    "quilon"
    "rajdhani"
    "ranade"
    "recia"
    "rosaline"
    "roundo"
    "rowan"
    "rx-100"
    "satoshi"
    "segment"
    "sentient"
    "sharpie"
    "stardom"
    "striper"
    "styro"
    "supreme"
    "switzer"
    "synonym"
    "tabular"
    "tanker"
    "technor"
    "teko"
    "telma"
    "trench-slab"
    "zina"
    "zodiak"
)

printf "{\n" > $OUT

for FONT in "${FONTS[@]}"
do
    HASH="$(nix-prefetch fetchzip --url "${URL}/${FONT}" --extension zip)"
    printf "  %s = "%s";\n" "$FONT" "\"$HASH\"" >> $OUT
done

printf "}\n" >> $OUT

printf "\"%s\"\n" "$(date -I)" > version.nix
